### PR TITLE
Use DOM to clean up navigation, allow us to deprecate children

### PR DESCRIPTION
**Pull request by trieloff**
- see https://github.com/adobe/helix-pipeline/issues/105

This PR (WIP) is using DOM manipulation to clean up the navigation, which is a bit more robust to HTML changes than operating on `children`.

I haven't removed the old code or adjusted the unit tests that access it, and I'm not 100% sure I caught your intended behavior, but the new code should be roughly equivalent.

### CODE REVIEW

**Comment by trieloff** [comment]
@kptdobe ready for review: I've ported the unit tests and also pinned the CircleCI docker image, which has been causing build failures.

**Comment by trieloff** [comment]
@kptdobe can I make a separate PR for that? This one should at least fix the build and smoke tests.

**Comment by trieloff** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging add177ceaa16672584b95cc9ba473d55869df7ee into 00765c63f33cd7a2ece6027f6bc1c4c82e303582 - [view on LGTM.com](https://lgtm.com/projects/g/adobe/project-helix.io/rev/pr-b0823fd5c47c73d74bcacbf425f64e48d054a69c)

**new alerts:**

* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Useless conditional
* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by trieloff** [comment]
This pull request **fixes 2 alerts** when merging 10f89c2fc8173ee98bf505533305b0afa6ac04b8 into 0df098ecfbc02de46a4005a164efed290a637fb6 - [view on LGTM.com](https://lgtm.com/projects/g/adobe/project-helix.io/rev/pr-c29f92293825eb32453c4bcdb1969a35093c193d)

**fixed alerts:**

* 1 for Useless conditional
* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by trieloff** [comment]
This pull request **fixes 2 alerts** when merging f80cfd4bba6b6b46aa6a6e838e43acb2cef7971c into 0df098ecfbc02de46a4005a164efed290a637fb6 - [view on LGTM.com](https://lgtm.com/projects/g/adobe/project-helix.io/rev/pr-baee1d7f1a346d7d132cd8a73f9814ea33c06ce9)

**fixed alerts:**

* 1 for Useless conditional
* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by trieloff** [comment]
@kptdobe look again.

**Comment by trieloff** [comment]
This pull request **fixes 6 alerts** when merging 73dd8c6f7e0014f7ca2f0262f2fe18ae56de4832 into de8d9e0f9b5dae1faef692d4a2eaa0e93c72cc57 - [view on LGTM.com](https://lgtm.com/projects/g/adobe/project-helix.io/rev/pr-4972846af863584e0c3d5111574904d815831252)

**fixed alerts:**

* 4 for Adobe Project Helix: Deprecated Children
* 1 for Useless conditional
* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kptdobe** [comment]
Now that I merged, I realized the `html.htl` is still using `content.children`...

**Pull request merged**
